name: release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0
      - run: mkdir ./build
      - run: mkdir ./build/dist
      - run: cp ./index.html ./build/index.html
      - run: cp ./dist/index.iife.js ./build/dist/index.iife.js
      - uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: web
          ITCH_GAME: bitsy-merge
          ITCH_USER: seansleblanc
          PACKAGE: build
          VERSION: ${{ steps.package-version.outputs.current-version}}
